<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>



    <xacro:property name="HULL_length" value="0.4"/>
    <xacro:property name="HULL_width" value="0.3"/>
    <xacro:property name="HULL_height" value="0.2"/>
    <xacro:property name="HULL_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_thickness" value="0.04"/>

    <!-- offsety bzdety -->
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- Macro do kół z roomby  -->
    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:macro name="create_wheel" params="prefix y_offset wheel_radius wheel_width">
        <link name="${prefix}_wheel_link">
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.01" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
        <origin xyz="0 ${y_offset} 0.015" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="${prefix}_wheel_link" />
        <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- koniec makro -->


    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1"/> 
    </material>

    <link name="base_link">

    </link>

    <joint name="core_joint" type="fixed">
        <parent link="base_link"/>
        <child link="core"/>
        <origin xyz="-0.1 0 0"/>
    </joint>

    <link name="core">
        <visual>
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}"/>
            <geometry>
                <box size ="${HULL_length} ${HULL_width} ${HULL_height}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}"/>
            <geometry>
                <box size ="${HULL_length} ${HULL_width} ${HULL_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${HULL_length}" y="${HULL_width}" z="${HULL_height}">
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- left wheel link -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${HULL_width/2+wheel_thickness/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>

        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

        </collision>
        <xacro:inertial_cylinder mass="1" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- right wheel link -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-HULL_width/2-wheel_thickness/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>

        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

        </collision>
        <xacro:inertial_cylinder mass="1" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- caster wheel -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="core"/>
        <child link="caster_wheel"/>
        <origin xyz="0.24 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="black"/>

        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="black"/>

        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

</robot>
