<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="HULL_length" value="0.335"/>
    <xacro:property name="HULL_width" value="0.265"/>
    <xacro:property name="HULL_height" value="0.138"/>
    <xacro:property name="HULL_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.066"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- HULL LINK -->

    <joint name="HULL_joint" type="fixed">
        <parent link="base_link"/>
        <child link="HULL"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="HULL">
        <visual>
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}"/>
            <geometry>
                <box size="${HULL_length} ${HULL_width} ${HULL_height}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}"/>
            <geometry>
                <box size="${HULL_length} ${HULL_width} ${HULL_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${HULL_length}" y="${HULL_width}" z="${HULL_height}">
            <origin xyz="${HULL_length/2} 0 ${HULL_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="HULL">
        <material>Gazebo/Yellow</material>
    </gazebo>


    <!-- //create wheel macro// -->

      <xacro:macro name="create_wheel" params="prefix y_offset wheel_radius wheel_width">
    <link name="${prefix}_wheel_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="0 ${y_offset} 0.015" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${prefix}_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>


    <!-- FRONT HULL SLOPE

    <link name="HULL_front_slope">
        <visual>
            <origin xyz="${HULL_length/2 - 0.1} 0 ${HULL_height/2}"/>
            <geometry>
                <box size="0.2 ${HULL_width} ${HULL_height/2}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="${HULL_length/2 - 0.1} 0 ${HULL_height/2}"/>
            <geometry>
                <box size="0.2 ${HULL_width} ${HULL_height/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="0.2" y="${HULL_width}" z="${HULL_height/2}">
            <origin xyz="0.1 0 0.05" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="HULL_front_slope_joint" type="fixed">
        <parent link="HULL"/>
        <child link="HULL_front_slope"/>
        <origin xyz="0 0 0" rpy="0 0 -0.7854"/>
    </joint> -->


    <xacro:create_wheel prefix="left" y_offset="${HULL_width / 2}"
      wheel_radius="${wheel_radius}" wheel_width="${wheel_thickness}" />
    <xacro:create_wheel prefix="right" y_offset="${HULL_width / -2}"
      wheel_radius="${wheel_radius}" wheel_width="${wheel_thickness}" />
    <!-- LEFT WHEEL LINK -->

    <!-- <joint name="left_wheel_joint" type="continuous">
        <parent link="HULL"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo> -->

    <!-- LEFT BACK WHEEL LINK -->

    <joint name="left_back_wheel_joint" type="continuous">
        <parent link="HULL"/>
        <child link="left_back_wheel"/>
        <origin xyz="${-HULL_length + 0.2} 0 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_back_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <gazebo reference="left_back_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <!-- <joint name="right_wheel_joint" type="fixed">
        <parent link="HULL"/>
        <child link="right_wheel"/>
        <origin xyz="${-HULL_length + 0.4} ${wheel_offset_y-HULL_width} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo> -->

    <!-- RIGHT BACK WHEEL LINK -->

    <joint name="right_back_wheel_joint" type="continuous">
        <parent link="HULL"/>
        <child link="right_back_wheel"/>
        <origin xyz="${-HULL_length + 0.2} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_back_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_back_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="HULL"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
